name: Build Tauri App

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-01
          targets: i686-pc-windows-msvc

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the app
        run: yarn release
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kuyland-launcher-windows-setup
          path: |
            src-tauri/target/i686-pc-windows-msvc/release/bundle/nsis/*.exe
            src-tauri/target/i686-pc-windows-msvc/release/bundle/msi/*.msi
          if-no-files-found: error
